services:
  web:
    build: .
    container_name: taller_gestion_conf_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: proy_sales.settings
