# Generated by Django 4.2 on 2024-07-04 21:34

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iva_image_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 21, 34, 40, 731535, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('A', 'En Percha'), ('B', 'De Baja')], default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100, validators=[proy_sales.utils.valida_numero_entero_positivo], verbose_name='Stock'),
        ),
    ]
